databases:
  - name: hack4delhi-db
    databaseName: hack4delhi
    plan: free

services:
  - type: web
    name: hack4delhi-ml-service
    env: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ml_transformer_service:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: hack4delhi-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node db/dbSetup.js && npm start
    plan: free
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: hack4delhi-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
